realty_parser/models.py
from peewee import (MySQLDatabase, Model, IntegerField, CharField, DateField, TextField,
                    FloatField, DoesNotExist, InternalError)

db = MySQLDatabase(database='realty',
                   user='root',
                   password='oruri448', threadlocals=True, host='mysql', port=3306)


class CianModel(Model):
    class Meta:
        database = db


class ItemsDB(CianModel):
    url = CharField()
    site = CharField()
    price = IntegerField(null=True)
    price_per_meter = IntegerField(null=True)
    rooms = CharField(null=True)
    total_square = FloatField(null=True)
    rooms_square = CharField(null=True)
    living_square = CharField(null=True)
    kitchen_square = CharField(null=True)
    wc = CharField(null=True)
    balcony = CharField(null=True)
    elevator = CharField(null=True)
    parking = CharField(null=True)
    window_look = CharField(null=True)
    issue_date = CharField(null=True)
    house_type = CharField(null=True)
    matherial_type = CharField(null=True)
    floor = CharField(null=True)
    floors = CharField(null=True)
    type_salary = CharField(null=True)
    region = CharField(null=True)
    city = CharField(null=True)
    district = CharField(null=True)
    microdistrict = CharField(null=True)
    street = CharField(null=True)
    house_num = CharField(null=True)
    JK_name = CharField(null=True)
    seller_phone = CharField(null=True)
    premium_status = CharField(null=True)
    publish_date = DateField(null=True)
    up_date = CharField(null=True)
    decoration = CharField(null=True)
    ad_text = TextField(null=True)
    views = CharField(null=True)

    def create_db(self):
        try:
            db.create_table(ItemsDB)
        except InternalError:
            pass

    @db.execution_context(with_transaction=False)
    def add_item(self, **kwargs):
        if not self.search_item(url=kwargs['url']):
            new_item = ItemsDB.create(**kwargs)
            ItemsDB.save(new_item)
        else:
            new_item = ItemsDB.get(url=kwargs['url'])
            new_item.price = kwargs['price']
            new_item.price_per_meter = kwargs['price_per_meter']
            new_item.issue_date = kwargs['issue_date']
            new_item.type_salary = kwargs['type_salary']
            new_item.seller_phone = kwargs['seller_phone']
            new_item.premium_status = kwargs['premium_status']
            new_item.up_date = kwargs['up_date']
            new_item.ad_text = kwargs['ad_text']
            ItemsDB.save(new_item)

    def search_item(self, url):
        try:
            return ItemsDB.get(ItemsDB.url == url)
        except DoesNotExist:
            return None

admin/blueprint.py
import tasks

from flask import Blueprint, jsonify
from flask import render_template


admin = Blueprint('admin', __name__, template_folder='templates')


@admin.route('/')
def index():
    return render_template('admin/index.html')


@admin.route('/run-task/<site>', methods=['GET'])
def run_task(site):
    task = tasks.start_parsing.delay(site)
    return jsonify(task_id=task.id, task_status=task.state)


@admin.route('/task-status/<id>')
def check_staus(id):
    task = tasks.start_parsing.AsyncResult(id)
    # info = tasks.start_parsing.get(id)
    response = {'status': task.state, 'result': task.result}
    return jsonify(response)

app.py
from flask import Flask
from celery import Celery
from config import Configuration

app = Flask(__name__)
app.config.from_object(Configuration)

celery = Celery('tasks', broker=app.config['CELERY_BROKER_URL'])
celery.conf.update(app.config)

from admin.blueprint import admin

app.register_blueprint(admin, url_prefix='/admin')

main.py
import view

from app import app

from realty_parser.models import ItemsDB

if __name__ == '__main__':
    db = ItemsDB()
    db.create_db()
    app.run(host='0.0.0.0', port=5000)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--My CSS Theme -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/mytheme.css' ) }}">

    <title>Hello, world!</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('index') }}">Realty parser</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('index') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('admin.index') }}">Run Parsers</a>
            </li>
        </ul>
    </div>
</nav>
{% block content %}

{% endblock %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<!--jQuery-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js" type="text/javascript"></script>
 <!--My JS Script -->
<script type="text/javascript" src="{{ url_for('static', filename='js/page.js') }}"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Url</th>
            <th scope="col">Views</th>
            <th scope="col">AD text</th>
        </tr>
        </thead>
        <tbody>
        {% for record in records %}
            <tr>
                <th scope="row">{{ record.id }}</th>
                <td><a href="{{ record.url }}">{{ record.url }}</a></td>
                <td>{{ record.views }}</td>
                <td>{{ record.ad_text }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}